### ISSUE TITLE
arrow-parens rule

### ISSUE THREAD

**Issue by xavhan** [SimpliField/eslint-config-simplifield#14]
Not a big fan of parens in single argument arrow functions

Their is a setting `["error", "as-needed"]` that allows us to write `a => 2a` instead of `(a) => 2a`, but force the parenthesis when they are mandatory (0 or 2+ args).

I advice to change ``["warning", "always"]` by `["error", "as-needed"]`, errors would be more meaningful.

**Comment by SebastienElet** [comment]
I like the airbnb rule about fat arrows : https://github.com/airbnb/javascript#arrows--one-arg-parens

Then i'm ok to remove parens if there is no braces.

**Comment by nfroidure** [comment]
Also like the @SebastienElet suggestion. I think it is meaningful to keep parens when the function body is heavy to better handle the visual structure of the code while it may be meaningless to add parens in short inline functions.

'as-needed' seems to be the closer configuration for it but i would have prefer an exact match for that rule. Anyone open to PR eslint ?

**Comment by nfroidure** [comment]
Let's start with some docs of the behavior we'd like to implement  https://github.com/nfroidure/eslint/commit/f35733bc9a384a4bd7604e636a1341b766e10f24
