### ISSUE TITLE
func-style rule

### ISSUE THREAD

**Issue by SebastienElet** [SimpliField/eslint-config-simplifield#22]
I have errors when i want to declare function with the following syntax

``` javascript
const shutdown = (code) => {}
```

To be valid, i should write

``` javascript
function shutdown(code) {}
```

@xavhan @gplancke @ArnaudSpanneut what is your opinion about this, should we move to the first syntax ?

**Comment by xavhan** [comment]
The second one was enforced by the JPapa styleguide, the 1st one is useful for a functional style. I think that now, we know what we are doing and _both_ can coexist.

**Comment by ArnaudSpanneut** [comment]
👍
