### ISSUE TITLE
Use YAML flow style instead of block style

### ISSUE THREAD

**Issue by SebastienElet** [SimpliField/eslint-config-simplifield#3]
L'utilisation du flow style, permet de facilement trier les rules par ordre alphabetique pour une meilleure lisibilité du fichier `.eslintrc`.

Par exemple :

``` yaml
  quotes:
    - 2
    - single
```

Devient : 

``` yaml
  quotes: [2, "single"]
```

Ensuite pour trier sous vim :

```
:/rules/+1,$sort
```

**Comment by nfroidure** [comment]
Finally using JSON ;)
