### ISSUE TITLE
[no-unused-vars] From error to warnings

### ISSUE THREAD

**Issue by nfroidure** [SimpliField/eslint-config-simplifield#4]
http://eslint.org/docs/rules/no-unused-vars.html

This rule is pretty handy but for functions parameters it is often suitable to have the complete function signature whenever you use the arguments or not.

By example for ExpressJS callback:

``` js
  return function catchAllFunction(err, req, res, next) {
```

it is usefull to keep the next arg even if it is not used right now.

We also could totally remove args checking but we would loose the information which is useful in some case. Best would be two separate rules to continue erroring on unused variable but only warning for unused args.

**Comment by SebastienElet** [comment]
In my opinion, we should rely on another tool to check quickly the function signature.

I will try [ternjs](https://github.com/ternjs/tern) which is available on most editors.

**Comment by SebastienElet** [comment]
The option `{ "args": "all" }` could permit this

**Comment by SebastienElet** [comment]
It's `{ "args": "none" }` ^^
