### ISSUE TITLE
Rule : padding-line-between-statements

### ISSUE THREAD

**Issue by SebastienElet** [SimpliField/eslint-config-simplifield#77]
http://eslint.org/docs/rules/padding-line-between-statements

This is opinionated, but i would like to use this rule as warning with the fallowing configuration : 
```javascript
{
  padding-line-between-statements: [
    'warning',
    { blankLine: 'always', prev: '*', next: 'return' },
  ]
}
```

To force a new line before any return.

**Comment by SebastienElet** [comment]
@gplancke @xavhan @ArnaudSpanneut @UaQuetzalcoatl what's your opinion about this ?

**Comment by xavhan** [comment]
Do not care if there is a way to fix potential warnings due to this change automatically.

**Comment by SebastienElet** [comment]
@xavhan : 

> The --fix option on the command line can automatically fix some of the problems reported by this rule.

It's just a question of readability
