### ISSUE TITLE
Migrate to eslint 1.5.0

### ISSUE THREAD

**Issue by nfroidure** [SimpliField/eslint-config-simplifield#9]
New rules in those releases:
http://eslint.org/blog/2015/08/eslint-1.2.0-released/#features
http://eslint.org/blog/2015/08/eslint-v1.3.0-released/#features

**Comment by xavhan** [comment]
- **1.5.x**
- **1.4.x**
  - autofixing
  - [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes.html)
  - [require-jsdoc](http://eslint.org/docs/rules/require-jsdoc.html)
  - [global-require](http://eslint.org/docs/rules/global-require.html)
  - [no-restricted-syntax](http://eslint.org/docs/rules/no-restricted-syntax.html)
  - [space-before-keywords](http://eslint.org/docs/rules/space-before-keywords.html)
- **1.3.x**
  - [no-useless-concat](http://eslint.org/docs/rules/no-useless-concat.html)
- **1.2.x**
  - [block-spacing](http://eslint.org/docs/rules/block-spacing.html)
  - [no-dupe-class-members](http://eslint.org/docs/rules/no-dupe-class-members.html)
  - [prefer-arrow-callback](http://eslint.org/docs/rules/prefer-arrow-callback.html)
  - [prefer-template](http://eslint.org/docs/rules/prefer-template.html)
